version: "3.5"
services:
  m3comparator:
    expose:
      - "9000"
    ports:
      - "0.0.0.0:9000:9000"
    networks:
      - backend
    image: "m3comparator:${REVISION}"
  m3query:
    expose:
      - "7201"
      - "7203"
    ports:
      - "0.0.0.0:7201:7201"
      - "0.0.0.0:7203:7203"
    networks:
      - backend
    image: "m3query:${REVISION}"
    volumes:
      - "./m3query.yml:/etc/m3query/m3query.yml"
  prometheus:
    expose:
      - "9090"
    ports:
      - "0.0.0.0:9090:9090"
    networks:
      - backend
    image: prom/prometheus:latest
    volumes:
      - "./:/etc/prometheus/"
  grafana:
    build:
      context: ./grafana
      dockerfile: grafana.Dockerfile
    expose:
      - "3000"
    ports:
      - "0.0.0.0:3000:3000"
    networks:
      - backend
    image: m3grafana:latest
  jaeger:
    networks:
      - backend
    image: jaegertracing/all-in-one:1.9
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "0.0.0.0:5775:5775/udp"
      - "0.0.0.0:6831:6831/udp"
      - "0.0.0.0:6832:6832/udp"
      - "0.0.0.0:5778:5778"
      - "0.0.0.0:16686:16686"
      - "0.0.0.0:14268:14268"
      - "0.0.0.0:14269:14269"
      - "0.0.0.0:9411:9411"
networks:
  backend:
