common: &common
  timeout_in_minutes: 20
  agents:
    queue: beefy-m3db
  retry:
    # Automatically retry failures one time.
    automatic:
      limit: 1
    # Allow manual retries.
    manual: true

steps:
  - name: "Codegen"
    command: make clean install-vendor test-all-gen
    env:
      CGO_ENABLED: 0
      GIMME_GO_VERSION: 1.12.x
    plugins:
        gopath-checkout#v1.0.1:
          import: github.com/m3db/m3
    <<: *common
  - name: "Unit %n"
    command: make clean install-vendor test-ci-unit
    parallelism: 4
    plugins:
      docker-compose#v2.5.1:
        run: app
        workdir: /go/src/github.com/m3db/m3
    <<: *common
